import type { Certificate, Product } from "./types"

export enum DownloadErrorCode {
  CERTIFICATE_NOT_FOUND = "CERTIFICATE_NOT_FOUND",
  FILE_NOT_ATTACHED = "FILE_NOT_ATTACHED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  NETWORK_ERROR = "NETWORK_ERROR",
  INVALID_FILE_DATA = "INVALID_FILE_DATA",
  DOWNLOAD_FAILED = "DOWNLOAD_FAILED",
}

export class DownloadError extends Error {
  code: DownloadErrorCode
  details?: string

  constructor(code: DownloadErrorCode, message: string, details?: string) {
    super(message)
    this.name = "DownloadError"
    this.code = code
    this.details = details
  }
}

export function getDownloadErrorMessage(err: unknown): string {
  if (err instanceof DownloadError) {
    switch (err.code) {
      case DownloadErrorCode.CERTIFICATE_NOT_FOUND:
        return "Sertifika bulunamadı. Lütfen sayfayı yenileyin veya başka bir sertifika deneyin."
      case DownloadErrorCode.FILE_NOT_ATTACHED:
        return "Bu sertifika için henüz bir dosya yüklenmemiş. Demo sürümü indiriliyor..."
      case DownloadErrorCode.PERMISSION_DENIED:
        return "Bu dosyayı indirmek için erişim izniniz yok. Lütfen sistem yöneticisiyle iletişime geçin."
      case DownloadErrorCode.NETWORK_ERROR:
        return "Bağlantı hatası. Lütfen internet bağlantınızı kontrol edip tekrar deneyin."
      case DownloadErrorCode.INVALID_FILE_DATA:
        return "Sertifika dosyası bozuk veya geçersiz. Lütfen tekrar yükleyin."
      case DownloadErrorCode.DOWNLOAD_FAILED:
        return "İndirme sırasında beklenmeyen bir hata oluştu. Lütfen tekrar deneyin."
    }
  }
  if (err instanceof Error) return err.message
  return "İndirme sırasında bilinmeyen bir hata oluştu."
}

/**
 * Check if browser supports modern download mechanism and
 * detect certain blocked-state conditions (e.g. in iframe, sandbox).
 */
function checkDownloadEnvironment(): { ok: boolean; error?: DownloadError } {
  try {
    if (typeof window === "undefined") {
      return {
        ok: false,
        error: new DownloadError(
          DownloadErrorCode.PERMISSION_DENIED,
          "Tarayıcı ortamı tespit edilemedi.",
        ),
      }
    }
    const canBlob = typeof Blob !== "undefined" && typeof URL !== "undefined"
    if (!canBlob) {
      return {
        ok: false,
        error: new DownloadError(
          DownloadErrorCode.DOWNLOAD_FAILED,
          "Tarayıcınız indirme özelliğini desteklemiyor.",
        ),
      }
    }
    return { ok: true }
  } catch (e) {
    return {
      ok: false,
      error: new DownloadError(DownloadErrorCode.DOWNLOAD_FAILED, "Ortam denetimi başarısız.", String(e)),
    }
  }
}

function triggerBrowserDownload(blob: Blob, fileName: string): Promise<void> {
  return new Promise((resolve, reject) => {
    try {
      const url = URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = fileName
      a.rel = "noopener"
      a.style.display = "none"
      document.body.appendChild(a)
      setTimeout(() => {
        a.click()
        a.remove()
        setTimeout(() => URL.revokeObjectURL(url), 5000)
        resolve()
      }, 0)
    } catch (e) {
      reject(
        new DownloadError(
          DownloadErrorCode.DOWNLOAD_FAILED,
          "Dosya indirilemedi.",
          e instanceof Error ? e.message : String(e),
        ),
      )
    }
  })
}

/** Escape text for inclusion in a PDF content stream. */
function esc(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)")
}

/**
 * Builds a minimal, valid single-page PDF document in-memory so the demo
 * "download" produces a real .pdf file. In production this would be replaced
 * by a signed URL to the stored certificate in blob storage.
 */
function buildDemoPdf(product: Product, cert: Certificate): Blob {
  const lines = [
    `HOMOLOGATION CERTIFICATE`,
    ``,
    `Certificate: ${cert.name}`,
    `Product: ${product.code}`,
    `Product family: ${product.family}`,
    `Region: ${cert.region}`,
    `Type: ${cert.type}`,
    `Issued: ${cert.issueDate}`,
    `Valid until: ${cert.expiryDate}`,
    ``,
    `This is a demo document generated by the Daiichi Infotainment Systems portal.`,
    `(No uploaded copy was attached for this certificate record.)`,
  ]

  let y = 760
  const textOps = lines
    .map((line) => {
      const op = `BT /F1 ${line === lines[0] ? 16 : 11} Tf 60 ${y} Td (${esc(line)}) Tj ET`
      y -= line === lines[0] ? 32 : 20
      return op
    })
    .join("\n")

  const content = `${textOps}`
  const objects: string[] = []
  objects.push(`<< /Type /Catalog /Pages 2 0 R >>`)
  objects.push(`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`)
  objects.push(
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>`,
  )
  objects.push(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`)
  objects.push(`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`)

  let pdf = `%PDF-1.4\n`
  const offsets: number[] = []
  objects.forEach((obj, i) => {
    offsets.push(pdf.length)
    pdf += `${i + 1} 0 obj\n${obj}\nendobj\n`
  })
  const xrefStart = pdf.length
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  offsets.forEach((off) => {
    pdf += `${String(off).padStart(10, "0")} 00000 n \n`
  })
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`

  return new Blob([pdf], { type: "application/pdf" })
}

function base64ToBlob(base64: string, mimeType: string): Blob {
  try {
    const byteChars = atob(base64)
    const byteArrays: Uint8Array[] = []
    const sliceSize = 512
    for (let offset = 0; offset < byteChars.length; offset += sliceSize) {
      const slice = byteChars.slice(offset, offset + sliceSize)
      const byteNumbers = new Array(slice.length)
      for (let i = 0; i < slice.length; i++) {
        byteNumbers[i] = slice.charCodeAt(i)
      }
      byteArrays.push(new Uint8Array(byteNumbers))
    }
    return new Blob(byteArrays, { type: mimeType || "application/octet-stream" })
  } catch (e) {
    throw new DownloadError(
      DownloadErrorCode.INVALID_FILE_DATA,
      "Dosya verisi okunamadı. Sertifika yeniden yüklenmelidir.",
      e instanceof Error ? e.message : String(e),
    )
  }
}

/**
 * Download a certificate. Returns a Promise so callers can handle
 * success / failure states. If the certificate has an uploaded file
 * (fileData) that file is downloaded verbatim, otherwise a demo PDF
 * is generated and downloaded (with FALLBACK status).
 */
export async function downloadCertificate(
  product: Product | null | undefined,
  cert: Certificate | null | undefined,
): Promise<{ ok: boolean; usedFallback: boolean; message?: string; error?: DownloadError }> {
  const envCheck = checkDownloadEnvironment()
  if (!envCheck.ok) {
    return { ok: false, usedFallback: false, error: envCheck.error }
  }

  if (!product || !cert) {
    const err = new DownloadError(
      DownloadErrorCode.CERTIFICATE_NOT_FOUND,
      "Sertifika veya ürün bulunamadı.",
    )
    return { ok: false, usedFallback: false, error: err }
  }

  const hasUploadedFile = Boolean(cert.fileData)

  try {
    let blob: Blob
    let fileName = cert.fileName || `${cert.name.replace(/\s+/g, "_")}.pdf`

    if (hasUploadedFile) {
      blob = base64ToBlob(cert.fileData!, cert.mimeType || "application/octet-stream")
    } else {
      blob = buildDemoPdf(product, cert)
    }

    await triggerBrowserDownload(blob, fileName)

    if (hasUploadedFile) {
      return {
        ok: true,
        usedFallback: false,
        message: `İndirme başarılı: ${fileName}`,
      }
    }
    return {
      ok: true,
      usedFallback: true,
      message: getDownloadErrorMessage(
        new DownloadError(DownloadErrorCode.FILE_NOT_ATTACHED, "Fallback demo indiriliyor."),
      ),
    }
  } catch (e) {
    if (e instanceof DownloadError) {
      return { ok: false, usedFallback: false, error: e }
    }
    return {
      ok: false,
      usedFallback: false,
      error: new DownloadError(
        DownloadErrorCode.DOWNLOAD_FAILED,
        "İndirme başarısız.",
        e instanceof Error ? e.message : String(e),
      ),
    }
  }
}
